---
# - name: "Apache installation using Docker"
#   hosts: prod
#   become: yes
#   vars:
#     ansible_sudo_pass: admin

#   pre_tasks:
#     - name: Install EPEL repo
#       package: name=epel-release state=present
#       when: ansible_distribution == "CentOS"

#     - name: Install python-pip
#       yum: name=python-pip state=present update_cache=yes

#     - name: Install docker python
#       pip: name=docker-py

#   tasks:
#     - name: Create Apache container
#       docker_container:
#         name: webapp
#         image: httpd
#         ports:
#           - "80:80"

- name: "Apache installation using docker"
  hosts: prod
  become: true
  vars:  
    ansible_sudo_pass: admin
  pre_tasks:
    - name: Install some package 
      package: name='{{ item }}' state=present
      when: ansible_distribution == "CentOS"
      loop:
        - epel-release
        - wget
        - git

    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: install python-pip
      command: python2.7 /tmp/get-pip.py

    - name: Install docker python
      pip: name=docker-py
    - name: Creates directory
      file:
        path: /home/admin/site
        state: directory

  tasks:
    - name: Copy website file template
      template:
        src: index.html.j2
        dest: /home/admin/site/index.html
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - "/home/admin/site/:/usr/local/apache2/htdocs/"