---
# - name: "Apache Installation"
#   hosts: prod
#   become: true
#   vars:
#     ansible_sudo_pass: admin
#   tasks:
#     - name: "Install dependencies"
#       ansible.builtin.yum:
#         name: python-requests
#     - name: "Create container"
#       community.docker.docker_container:
#         name: webapp
#         image: httpd
#         ports:
#           - "80:80"

# - name: "Apache installation using docker"
#   hosts: prod
#   vars:
#      ansible_sudo_pass: admin
#   pre_tasks:
#   - name: Install python-pip state=present update_cache=yes
#     yum: name-python-pip

#   - name: Install docker python
#     pip: name-docker-pip
#     tasks:
#   - name: Create apache container
#     docker_container:
#        name: webapp
#        image: httpd
#        ports:
#             -"80:80"

# - name: "Apache installation using docker"
#   hosts: prod
#   become: true
#   vars:
#      ansible_sudo_pass: admin
#   pre_tasks:
#     - name: Install EPEL repo
#       package: name=epel-release state=present
#       when: ansible_distribution == "CentOS"
#     - name: download pip script
#       get_url:
#         url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
#         dest: /tmp/get-pip.py
#     - name: install python-pip
#       command: python2.7 /tmp/get-pip.py
#     - name: Install docker python
#       pip: name=docker-py
#   tasks:
#     - name: Create Apache container
#       docker_container:
#         name: webapp
#         image: httpd
#         ports:
#           - "80:80"

- name: "Apache installation using Docker"
  hosts: prod
  become: yes
  vars:
    ansible_sudo_pass: admin

  pre_tasks:
    - name: Install EPEL repo
      package:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install python-pip
      yum:
        name: python-pip
        state: present
        update_cache: yes
    
    - name: Update pip
      pip:
        name: pip
        state: latest

    - name: Install docker Python library
      pip:
        name: docker
        state: present

    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

  tasks:
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
